### ISSUE TITLE
Additional wiki information for .env var MARIADB_DATA_IMAGE

### ISSUE THREAD

**Issue by grahamethompson** [govCMS/GovCMS#1]
https://govcms.gov.au/wiki-vars#MARIADB_DATA_IMAGE

For the PaaS peeps possibly add that if the mariadb variable is commented out, backups of the mariadb image to the gitlab registry will not occur.

something like
>An existing MariaDB-based Docker image. This will usually be your nightly database backup (created by the platform), but can be a generic pre-installed GovCMS. If this is not set, various processes like GitLab will install GovCMS Drupal profile by default *and not backup a nightly sanitized production database image to the gitlab registry*.

**Comment by grahamethompson** [comment]
When new projects are created from the scaffold multiple `MARIADB_DATA_IMAGE` entries are present in the `.env` file. 
This breaks container backups in gitlab.

New project .env example. 
```
##
# This file contains per-project environment variables.
# It is used by Ahoy, Docker-compose, Lagoon, and other scripts to read default values.
# Copy this file to '.env' to make docker-compose use overridden values.
#

# https://govcms.gov.au/wiki-vars#COMPOSE_PROJECT_NAME
COMPOSE_PROJECT_NAME=xxxxxx

# https://govcms.gov.au/wiki-vars#DEV_MODE
DEV_MODE=true

# https://govcms.gov.au/wiki-vars#GOVCMS_IMAGE_VERSION
#GOVCMS_IMAGE_VERSION=latest

# https://govcms.gov.au/wiki-vars#LAGOON_ENVIRONMENT_TYPE
LAGOON_ENVIRONMENT_TYPE=local

# https://govcms.gov.au/wiki-vars#LOCALDEV_URL
LOCALDEV_URL=http://dese-d8.docker.amazee.io

# https://govcms.gov.au/wiki-vars#MARIADB_DATA_IMAGE
MARIADB_DATA_IMAGE=gitlab-registry-production.govcms.amazee.io/org/project/mariadb-drupal-data

# https://govcms.gov.au/wiki-vars#STAGE_FILE_PROXY_URL
STAGE_FILE_PROXY_URL=https://xxxxxxx.govcms.amazee.io

# https://govcms.gov.au/wiki-vars#X_FRAME_OPTIONS
X_FRAME_OPTIONS=SameOrigin

# https://govcms.gov.au/wiki-vars#VOLUME_FLAGS
#VOLUME_FLAGS=cached
#MARIADB_DATA_IMAGE=gitlab-registry-production.govcms.amazee.io/new/project/mariadb-drupal-data
```

**Comment by thisisalistairsaccount** [comment]
Thanks @thompsong I've added in the information into the Wiki
