### ISSUE TITLE
What is the plan for stage_file_proxy in GovCMS 9 ? Module is unlisted

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [govCMS/GovCMS#126]
Hi Team,

I've checked:
- https://github.com/govCMS/GovCMS/issues/17
- https://www.govcms.gov.au/support/are-you-ready-drupal-9/transition-drupal-8-drupal-9
- https://www.govcms.gov.au/support/are-you-ready-drupal-9/govcms-drupal-9

Module is unlisted so unsure of GovCMS9 inclusion plan.

**Comment by yvonne-norris** [comment]
Hi Joshua,
You won't see it in my documentation because the stage_file_proxy module is not part of the distribution layer of GovCMS D9. 
As with D8 it will only exist at the lagoon layer. I have  added this to the backlog to be looked into.

**Comment by joshua-graham-adelphi** [comment]
ok thanks @yvonne-norris  :-)

**Comment by pandaskii** [comment]
I will close this issue for now. Pls, feel free to ask if you have any further questions :)
