### ISSUE TITLE
Add Layout Builder Modal module to GovCMS

### ISSUE THREAD

**Issue by Benjen** [govCMS/GovCMS#186]
** What value does this module/package add to GovCMS?

Makes it much easier to edit layout configuration in Layout Builder.

** Please provide a brief outline of what this module does.

This module lets you add and configure existing blocks in a modal in the Layout Builder UI.  The size of the modal is significantly larger than the default offpage form provided by Drupal core which is very small making it difficult to work with.

** Who does this module benefit:
[ ] end users
[ ] content editors
[ x ] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?

Can't really replicate this functionality without rebuilding the complete functionality as a custom module.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.

This functionality cannot be readily replicated by other means.

** What is the maintenance and support status of the module. Describe the issue queue activity.

- Three maintainers.
- Latest release: 8.x-1.1 (29 April 2020)
- Supports Drupal 9
- Bug reports: 21 (7 open)
- Pending patches: 5

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?

Adds permission to "Administer Layout Builder Modal".

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

No sure.

** Is the module designed to capture anonymous user data?

No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.

n/a (this module doesn't affect rendered output).

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?

- 5,689 website report using this module.

** Additional information

n/a

**Comment by pameeela** [comment]
Big +1 to this - I came here to make the same request.

We are using this module on all sites where we use Layout builder. The user experience without it is quite poor.

**Comment by thisisalistairsaccount** [comment]
Tied to Drupal 8 issue at https://github.com/govCMS/GovCMS8/issues/616

**Comment by thisisalistairsaccount** [comment]
Layout Builder Modal has been included in our 2.4.0 release and is now available for those building or working on Drupal 9 sites https://github.com/govCMS/GovCMS/releases/tag/2.4.0
