### ISSUE TITLE
Identify the modules in GovCMS 8 having issues for supporting 9

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS#2]
## Problem/Motivation

Please share if you find any modules in the current GovCMS8 distribution can be put into this list

This list will be updated with more details with each module. For example, architectural issues or a missing version compatible in `.info.yml` file

| Module | latest version | Notes |
| --- | --- | --- |
|events_log_track|8.x-2.0|No D9 support https://www.drupal.org/project/issues/events_log_track?categories=All|

From level 1 to level 4:
- The module is compatible but it just needs an updated .info file (easy)
- The module has unresolved deprecated code that might be easily updated (easy)
- The module has architectural issues (red flag)
- The module maintainer has declared end-of-life for that module and will not maintain a D9 version (critical)

**Comment by simesy** [comment]
Can we please do more detail on "no d9 support". here are the possible meanings in my mind and the impact could be dramatically different depending on the reason.

1. The module is compatible but it just needs an updated .info file (**easy**)
2. The module has unresolved deprecated code that might be easily updated (**easy**)
3. The module has architectural issues (**red flag**)
4. The module maintainer has declared end-of-life for that module and will not maintain a D9 version (**critical**)

**Comment by pandaskii** [comment]
@simesy Yes, we will update the list with more details together

**Comment by larowlan** [comment]
Might be time to move on from context?
Components now has a release, see https://drupal.slack.com/archives/C1BMUQ9U6/p1594628140170400?thread_ts=1594628140.170400
Module filter has core equivalent (since 8.0)

**Comment by simesy** [comment]
No other modules have a dependency on `context` which is good. Personally I sometimes use it to do weird things like set active trail. But it's a lot of code for such tiny things.

**Comment by simesy** [comment]
@pandaskii what are the usage stats for graphql? I would be super surprised if anyone is using it on saas.

**Comment by pandaskii** [comment]
@simesy Good news to graphql module the new release can support 9

I see your point, not essential but we are trying to track all the modules in the current GovCMS8 distribution

**Comment by pandaskii** [comment]
`context` dev branch is good now, hopefully, a release will happen very soon

**Comment by joshua-graham-adelphi** [comment]
field_group is still planned to be included in Govcms 9 ? the govCMS site says it's not compatible but no notes on it?

https://www.govcms.gov.au/support/are-you-ready-drupal-9/transition-drupal-8-drupal-9

**Comment by pandaskii** [comment]
@joshua-graham-adelphi field_group is included in GovCMS9

https://github.com/govCMS/GovCMS/blob/02d518369eb8aa3b6a850a846da2015aee258c63/composer.json#L59

**Comment by pandaskii** [comment]
A beta3 release is ready https://www.drupal.org/project/media_entity_file_replace/releases/8.x-1.0-beta3

And this will need a review then we can see if we can update it.

**Comment by pameeela** [comment]
config_ignore did an RC release this morning with D9 support: https://www.drupal.org/project/config_ignore/releases/8.x-2.3-rc1

**Comment by pandaskii** [comment]
config_ignore (8.x-2.3) will be added into distribution

**Comment by pandaskii** [comment]
Close it and we will create a new Github issue on a per-module basis.

thanks everyone input in this issue
