### ISSUE TITLE
Add block_visibility_conditions module to GovCMS

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [govCMS/GovCMS#203]
** What value does this module/package add to GovCMS?

More block condition flexibility.

** Please provide a brief outline of what this module does.

Use case:
- Show a block on all pages except specific node types. (e.g. campaign page)

Why doesn't Drupal cover this use case?
- OOTB Drupal node type condition does not validate for non-node pages. So the block will ONLY show on node pages & only that node page is not the specific node type. (Therefore, on views pages - the block does not show - where it should)

Module provides:
Ability to show the block on non-node pages + NOT selected node types. 

Note; module currently only works for the current page, not the set block contextual value.
@see https://www.drupal.org/project/block_visibility_conditions/issues/3213301

** Who does this module benefit:
[X] end users
[ ] content editors
[X] site builders
[X] themers
[X] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?

Workaround uses add a preprocess_page hook to unset the block in custom code condition.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.

N/A

** What is the maintenance and support status of the module. Describe the issue queue activity.

Low support status due to being a simple module.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?

N/A

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

Added extra block config dependency. 

** Is the module designed to capture anonymous user data?

N/A

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.

No affect on render cache.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?

Since, it is simple, no major breakages are expected (needs Drupal 9 testing though)

** Additional information

**Comment by joshua-graham-adelphi** [comment]
Related issue #99

**Comment by thisisalistairsaccount** [comment]
https://www.drupal.org/project/block_visibility_conditions

Hi @joshua-graham-adelphi noting the lack of coverage on the module from a security advisory policy perspective, GovCMS is suggesting we focus on #99 - while it doesn't give checkbox like options for content type exclusions, content types that are set against certain paths could be covered and meet the same end goal. 

If you have anything you can contribute to the module request on that one (noting we're missing some detail as part of that request) it would be appreciated so we can investigate and assess.
