### ISSUE TITLE
Add SVG Image module to GovCMS

### ISSUE THREAD

**Issue by Benjen** [govCMS/GovCMS#263]
** What value does this module/package add to GovCMS?

Enables site authors to upload SVG images as well as rasterised images to the same image field. This was possible in GovCMS7.

** Please provide a brief outline of what this module does.

This module changes the default image field widget and formatter to allow use SVG image with the standard Image field.

** Who does this module benefit:
[ ] end users
[ X ] content editors
[ X ] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?

Not possible without the creation of a custom module.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.

Cannot provide the functionality via the site theme as one needs use a custom module.

** What is the maintenance and support status of the module. Describe the issue queue activity.

The current stable release is 8.x-1.14 (4 June 2020) and is covered by the Drupal Security team.  There are 108 issues (33 open and 4 RTBC) in the issue queue.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?

This module does not introduce any new permissions. To use this module a user must be able to configure and/or use an image field.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

The module makes use of Drupal's plugin system and does not modify any existing database tables.

** Is the module designed to capture anonymous user data?

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.

This module does not alter the cacheability of a image field to which it is applied.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?

Over 33,000 Drupal 8 sites report using this module. Module code base appears to follow Drupal coding practices.

** Additional information

N/A

**Comment by thisisalistairsaccount** [comment]
Hi @Benjen there's security concerns around using SVG when we consider the platform. While the module gets updated and is managed, it's not something that we want to manage as another point of concern. I will close this as we won't progress this one along.
