### ISSUE TITLE
Vimeo videos with domain-level privacy setting break oEmbed

### ISSUE THREAD

**Issue by pameeela** [govCMS/GovCMS#266]
If Vimeo videos are using domain privacy settings, they cannot be added to the media library as remote videos. The Vimeo oEmbed endpoint requires a whitelisted referrer to be sent with the request in order to provide the metadata.

This is captured in a Drupal core issue here: https://www.drupal.org/project/drupal/issues/3056124

We are currently using this patch in our development environment to get around the issue: https://www.drupal.org/project/drupal/issues/3056124#comment-13611240

The current consensus on the issue is that this is an edge case that should not be fixed in core. The suggestion is to resolve the issue with a contrib module, however, this module doesn't currently exist.

So the options for supporting this are:
- Use one of the existing patches against core
- Develop a contrib module for it

As each of these requires GovCMS to make a change to the distro, it is not clear what the path is to unblock this.

**Comment by thisisalistairsaccount** [comment]
A module has been created called Media Vimeo Domain Privacy. It has also been marked with a stable release - https://www.drupal.org/project/media_vimeo_domain_privacy

**Comment by thisisalistairsaccount** [comment]
Noting the option is available to use Media Vimeo Domain Privacy on GovCMS sites, I will close this issue.
