### ISSUE TITLE
GovCMS9 Composer Create-Project instructions don't work

### ISSUE THREAD

**Issue by ahrib** [govCMS/GovCMS#291]
Composer Create-Project instructions for the 2.x branch 
https://github.com/govCMS/GovCMS#via-composer-create-project

command
```
composer create-project --stability dev --prefer-dist govcms/govcms-project MY_PROJECT
```

**result**
```
[InvalidArgumentException] Could not find package govcms/govcms-project with stability dev.
```

**expected result**
that this works

**Comment by pandaskii** [comment]
@ahrib thanks for reporting this issue.

Committed the 2.x branch for it

https://github.com/govCMS/govcms-project

https://packagist.org/packages/govcms/govcms-project

**Comment by ahrib** [comment]
looks good, thank you
