### ISSUE TITLE
new project setup via Composer vs source is inconsistent

### ISSUE THREAD

**Issue by ahrib** [govCMS/GovCMS#292]
Setting up a new project via Composer  and setting up a new project from source result in _radically_ different composer.json files

* https://github.com/govCMS/GovCMS#via-composer-create-project
* https://github.com/govCMS/GovCMS#installation-from-source

Expected behaviour
1. Consistency. As per the documentation "Composer create-project is the same as doing a git clone, followed by a composer install."
2. Ability to pin to a particular branch (e.g. 1.x, 2.x-master) via composer.json regardless of setup method chosen (not possible with the install from source method)

**Comment by pandaskii** [comment]
@ahrib thanks for reporting this issue.

The project template can be found here https://github.com/govCMS/govcms-project/blob/2.x/composer.json

In this file, govcms/govcms version can be changed for pointing to a tag or branch.

This project template can be used in local or other environment except on the GovCMS platform (Lagoon). 

If you have a SaaS site on the GovCMS platform (Lagoon), you will not be able to change it.

**Comment by ahrib** [comment]
Thanks Joseph, that is very helpful. 

The team here is using both the 1.x and 2.x-master branches (until we complete the transition to 2.x)

**Comment by pandaskii** [comment]
@ahrib GovCMS d8 has a different template https://github.com/govCMS/GovCMS8-project/blob/1.x/composer.json

It is deprecated and only support composer ~1

But it could be useful for you migration.
