### ISSUE TITLE
Add information about pv to the wiki

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [govCMS/GovCMS#3]
Add below "Navigate to the project location, and import the database into the test container"

<details>
  <summary>Using PV to import view database import progress</summary>

Tested in windows (git bash) / Linux:

Install pv utility in docker:

        docker-compose exec cli apk update
        docker-compose exec cli apk add pv

Import Plain SQL file:

        # Get size of file in bytes.
        size=$(wc -c /path/to/database.sql | awk '{print $1}')
        # If using windows alias - don't use winpty for this.
        unalias docker-compose
        cat /path/to/database.sql | docker-compose exec -T cli bash -c "pv -f -s $size | drush sql-cli"
        # View progress
        $ 10 MB 0:00:00 [2.28MiB/s] [>                                  ]  0% ETA 0:15:00
        # If using windows alias - add back winpty for this.
        alias docker-compose="winpty docker-compose"

Gzipped SQL file (myfile.sql.gz)

        # Get size of file in bytes.
        size=$(wc -c /path/to/database.sql.gz | awk '{print $1}')
        # If using windows alias - don't use winpty for this.
        unalias docker-compose
        cat /path/to/database.sql.gz | docker-compose exec -T cli bash -c "pv -f -s $size | gunzip | drush sql-cli"
        # View progress
        $ 10 MB 0:00:00 [2.28MiB/s] [>                                  ]  0% ETA 0:15:00
        # If using windows alias - add back winpty for this.
        alias docker-compose="winpty docker-compose"

</details>

**Comment by joshua-graham-adelphi** [comment]
I can't seem to edit wiki directly - i used to be able to..

**Comment by pandaskii** [comment]
@joshua-graham-adelphi Pls try again, could be my bad to tick the wrong box :)

**Comment by joshua-graham-adelphi** [comment]
That worked - thanks!
