### ISSUE TITLE
Webform 6.x submodule (Submissions Export/Import) patch available to fix import issue

### ISSUE THREAD

**Issue by AtamDhillon** [govCMS/GovCMS#308]
Hi team,
I came across this issue while preparing a database and had to import some submissions to a webform.
The submodule within Webform allows you to export and import submissions as CSV.
The import failed to apply the values for "Submitted to" field.

I then raised it with Webform maintenance team and Jacob has now provided a patch for this fix.
The issue and fix can be found at - https://www.drupal.org/project/webform/issues/3231494#comment-14213014.

I believe the patch should be addressed as part of the Webform module functionality and applied to the distribution as well.
All yours to assess and address.

Regards
Atam Dhillon

**Comment by thisisalistairsaccount** [comment]
Thanks for putting this out here on Github @AtamDhillon for others to see in the community. 

We will keep this open while we wait for the Webform module to have it included as part of a release for the module.

**Comment by AtamDhillon** [comment]
Hi team,
Just came across another issue that relates to improved tokens for webform.
I am told by Jacob in below post (link) that a better improved version of tokens for webforms also appear to have not applied yet to the version we are using on SaaS distro.
Could you look into that too and may help with something I was trying to achieve.
I understand this may be a while based on whitelisted version.
Comment#5 - https://www.drupal.org/project/webform/issues/3232401#comment-14257600

**Comment by thisisalistairsaccount** [comment]
Hi @AtamDhillon just going back and reviewing this, it seems as though https://www.drupal.org/project/webform/issues/3231494 was included in the 6.1.0 release at https://www.drupal.org/project/webform/releases/6.1.0 and we've updated the GovCMS distro to the more recent 6.1.2.
