### ISSUE TITLE
Add Media file delete module to GovCMS

### ISSUE THREAD

**Issue by jibran** [govCMS/GovCMS#314]
**What value does this module/package add to GovCMS?**

Currently, file deletion is not supported on SaaS, and temporary files are not deleted from the system. As a result, site owners have no method to remove files from their sites and have to create a ticket to request file deletion. This process is quite confusing for non-technical editors, and we field many enquiries about this topic. The situation is documented at https://www.govcms.support/support/solutions/articles/51000107026-why-aren-t-files-with-0-usage-being-removed-from-our-site-

Media file delete gives content editors the option to delete the associated file when deleting a media entity.

**Please provide a brief outline of what this module does.**

* Give content editors the option to delete the associated file when deleting a media entity
* Prevents deletion if the file is in use in other locations
* Prevents deletion if the user does not have access
* Adds a new 'delete any file' permission, allowing power-users to bypass core's You can only delete files you own behaviour

** Who does this module benefit:**
- [ ] end users
- [x] content editors
- [ ] site builders
- [ ] themers
- [x] developers
 
**How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?**

This functionality can't be recreated by writing custom code in the theme.

**If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.**

No, this module doesn't provide any front-end functionality for the theme.

**What is the maintenance and support status of the module. Describe the issue queue activity.**

The module is actively maintained. As per d.o., 129 sites report using this module. There are no active bugs in the issue queue at this moment.

**What permissions are needed to utilise the module (and are any new permissions provided by the module)?**

The module provides 'Delete any file' permission.

**Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?**

The module doesn't alter the schema for existing entities. It only adds the option to delete the associated file of media entity.

**Is the module designed to capture anonymous user data?**

No

**Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.**

The module adds additional functionality and has nothing to do with cacheability.

**What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?**

 `larowlan` is the author and maintainer of the module. He is a Drupal core committer, the only one based in Australia, and a member of the Drupal security team.

**Additional information**

See discussion in https://github.com/govCMS/GovCMS/issues/231

**Comment by jibran** [comment]
The module can be found at https://www.drupal.org/project/media_file_delete.

**Comment by thisisalistairsaccount** [comment]
Hi @jibran , 

The issue currently faced with file deletion on GovCMS relates to the upstream issues identified on Drupal.org in relation to garbage collection for Drupal 8 and continue into 9:

- https://www.drupal.org/project/drupal/issues/2810355
- https://www.drupal.org/project/drupal/issues/2821423

While the file deletion module suggested among others like https://github.com/govCMS/GovCMS/issues/231 help to address a user problem, if garbage collection isn't accurate or safely handled like in Drupal 7, we move a painful process for deletion via our Service Desk into a more risky solution for sites and its documents/media with availability of material. 

Customers can request garbage collection to be turned on for 8/9 sites, but we would recommend limited windows noting the risk involved and the unexpected nature of what may be deleted.

We are looking at options to have a safe way for file deletion because it is an issue for customers. This module request will be considered as part of that broader work.

**Comment by thisisalistairsaccount** [comment]
Just to update, we are currently reviewing the Media File Delete option https://www.drupal.org/project/media_file_delete internally.

**Comment by silverham** [comment]
What is the recommended workaround in the mean time until this module is introduced to delete file entities manually?

**Comment by thisisalistairsaccount** [comment]
Hi @silverham 

Currently, requests to the Service Desk with file URLs and their IDs to delete with relevant project details.

However, next week (Tue/Wed) brings a new release, release notes and deployment for GovCMS. This will include Media File Delete for SaaS sites :)

**Comment by silverham** [comment]
That's great @thisisalistairsaccount! For already orphaned file entities without a parent media entity, created before this issue, even with this module, they still can't be removed though as there isn't UI button :-( (@see https://www.drupal.org/project/drupal/issues/2949017#comment-13793615 & https://www.drupal.org/project/drupal/issues/2936175)

So besides creating a service desk request with file URLs and File Ids, i also found another option which can achieve the goal of removing the orphan file entity without custom code:
- (Once Media File Delete lands) Create new catch-all media type, like the generic document file media type, which has a file field which allows all file extensions with an entity browser, then create a temporary 'catch-all' media entity, use entity browser to select the the orphan file entity, then delete the newly created media entity and tick the box to delete the original file entity - problem solved! :-)

**Comment by thisisalistairsaccount** [comment]
Hi All,

Media File Delete has been added to the GovCMS distribution as part of 2.16.0 - https://github.com/govCMS/GovCMS/releases/tag/2.16.0

Those running SaaS sites can request the module to be enabled via the GovCMS Service Desk.

@silverham that's a great approach to assist with orphan files!
