### ISSUE TITLE
Patch for Token that is flooding DBLog with Notices

### ISSUE THREAD

**Issue by TobyWild** [govCMS/GovCMS#326]
URL: https://www.drupal.org/project/token/issues/3154183

PHP 7.4+ issue with Token.  This notice causes a flood of errors in the DB Log.

**Comment by thisisalistairsaccount** [comment]
Hi @TobyWild I'm led to believe that this patch might have been rolled in as part of the Token's 1.9 release, which we have in the distribution. It doesn't seem to be listed on changes/bugs but seems to be there... 

Can you or someone else confirm?

**Comment by pellegs** [comment]
We've just released D9 with Tokens upgraded to 1.10.  Assuming this has been resolved.  
https://www.drupal.org/project/token/releases/8.x-1.10

**Comment by thisisalistairsaccount** [comment]
Hi @TobyWild I've taken a look at 1.10 and can see it's part of the **token.module** file. I'll close this as I think this has been resolved with the module update. Happy to reopen if needed.
