### ISSUE TITLE
2.x - Profile install includes content type dependent functionality

### ISSUE THREAD

**Issue by steveworley** [govCMS/GovCMS#33]
A fresh install of the profile results in the following errors (when viewing the homepage and trying to edit the Welcome node)

```
$ GET /node/1/edit
The website encountered an unexpected error. Please try again later.
Error: Call to a member function getPreviewMode() on null in Drupal\node\NodeForm->actions() (line 218 of core/modules/node/src/NodeForm.php).
```

```
$ GET /
The website encountered an unexpected error. Please try again later.
Error: Call to a member function displaySubmitted() on null in template_preprocess_node() (line 528 of core/modules/node/node.module)
```

This problem occurs because the profile creates a node and attempts to assign it to the `govcms_standard_page`, the node is created successfully but because the content type doesn't exist the node is not create correctly and causes the above errors.

https://github.com/govCMS/GovCMS/blob/2.x/govcms.install#L38

Since the profile doesn't enable the content type modules the base profile cannot create nodes (as no content types are present with a blank install). 

**Mitigation**

- Enabling `govcms_standard_page` automatically assigns the content type and corrects the problem

**Proposed solution**

- Move the node create to a content type specific install hook

**Comment by pandaskii** [comment]
Fixed after recents commits. thanks guys for working in the PRs
