### ISSUE TITLE
Rest UI and some other modules

### ISSUE THREAD

**Issue by rsau** [govCMS/GovCMS#330]
Hi GovCMS 

I couldn't see anything on `admin/config/services/rest`  even though `restui` module was enabled. 

Trying to find out why it isn't working , I found out that module is located at `/app/web/sites/all/modules/` 

``` 
-rw-rw-r-- 1 root root  450 Sep 27 23:25 README.md
drwxrwxr-x 2 root root 4096 Sep 27 23:25 config_ignore
drwxrwxr-x 2 root root 4096 Sep 27 23:25 event_log_track
drwxrwxr-x 2 root root 4096 Sep 27 23:25 govcms8_uikit_starter
drwxrwxr-x 2 root root 4096 Sep 27 23:25 govcms_admin_theme
drwxrwxr-x 2 root root 4096 Sep 27 23:25 govcmsui
drwxrwxr-x 2 root root 4096 Sep 27 23:25 graphql
drwxrwxr-x 4 root root 4096 Sep 27 23:25 lagoon
drwxrwxr-x 2 root root 4096 Sep 27 23:25 login_security
drwxrwxr-x 2 root root 4096 Sep 27 23:25 module_filter
drwxrwxr-x 2 root root 4096 Sep 27 23:25 page_manager
drwxrwxr-x 2 root root 4096 Sep 27 23:25 page_manager_ui
drwxrwxr-x 2 root root 4096 Sep 27 23:25 permissions_by_entity
drwxrwxr-x 2 root root 4096 Sep 27 23:25 permissions_by_term
drwxrwxr-x 2 root root 4096 Sep 27 23:25 restui
```

Most of the above only have `*.info.yml` files 

```
./login_security:
total 4
-rw-rw-r-- 1 root root 69 Sep 27 23:25 login_security.info.yml

./module_filter:
total 4
-rw-rw-r-- 1 root root 68 Sep 27 23:25 module_filter.info.yml

./page_manager:
total 4
-rw-rw-r-- 1 root root 67 Sep 27 23:25 page_manager.info.yml

./page_manager_ui:
total 4
-rw-rw-r-- 1 root root 70 Sep 27 23:25 page_manager_ui.info.yml

./permissions_by_entity:
total 4
-rw-rw-r-- 1 root root 76 Sep 27 23:25 permissions_by_entity.info.yml

./permissions_by_term:
total 4
-rw-rw-r-- 1 root root 74 Sep 27 23:25 permissions_by_term.info.yml

./restui:
total 4
-rw-rw-r-- 1 root root 61 Sep 27 23:25 restui.info.yml
```

How can we install Rest UI module ?

**Comment by thisisalistairsaccount** [comment]
Hi @rsau currently there are some security considerations around the use of Rest UI on SaaS sites. In the interim we have removed Rest UI from the distribution. 

We will be considering things around Rest and APIs in 2022, but don't have a decision to communicate at this time. We would be keen to understand use cases and thoughts on where you would be looking to use Rest UI among other API functionality.

**Comment by rsau** [comment]
Hi @thisisalistairsaccount   

 We noticed that rest endpoint exposes revision log message on nodes to anonymous users.  
Our editing team uses it to add revision info in the format `Ticket_no - revision_message - name_of_ticket_creator`  
When looking to see if Rest UI has a way to hide that data, I found out that module is actually not installed even though it shows up in installed list.
