### ISSUE TITLE
Layout builder - cross site error when enabling the module

### ISSUE THREAD

**Issue by gigimaor** [govCMS/GovCMS#371]
On new Drupal 9 SaaS installation on local dev environment.

After the Layout builder module is enabled (drush en layout_builder), it crashes the website cross pages:

The website encountered an unexpected error. Please try again later.
Error: Call to a member function getLabel() on null in Drupal\layout_builder\Plugin\Derivative\FieldBlockDeriver->getDerivativeDefinitions() (line 113 of core/modules/layout_builder/src/Plugin/Derivative/FieldBlockDeriver.php).

The solution to solve this error is to patch Drupal core. See this link
https://www.drupal.org/project/drupal/issues/2985882

The patch configured in /app/custom/composer/patches.json
{
  "patches": {
    "drupal/core": {
      "Call to a member function getLabel() after enabling layout_builder": "https://www.drupal.org/files/issues/2020-04-08/2985882-field-85.patch"
    }
  }
}

**Comment by thisisalistairsaccount** [comment]
Hi @gigimaor can you provide a test case for this?

We'll have a test internally and see if we get similar or different results.

Thanks

**Comment by gigimaor** [comment]
This issue was caused by the bad migration process from D7 to D9, and fixed with a custom module that dictates the migration process.

The patch is not necessary to implement globally in this case.

This ticket may be closed.

Thanks

**Comment by thisisalistairsaccount** [comment]
Thanks for the update @gigimaor i'll close this
