### ISSUE TITLE
Add Media Bulk Upload module to GovCMS

### ISSUE THREAD

**Issue by isaactownsend** [govCMS/GovCMS#466]
### What value does this module/package add to GovCMS?
The module replaces the lost functionality of bulk upload through a dropzone field that was supported by GovCMS Media module until last update. It enhances content editor productivity and user experience and is readily available and well supported.

### Please provide a brief outline of what this module does.
It allows editors to upload bulk files in batches through a dropzone form rather than using the media->add button which can be a workflow problem if large batches of media items are being uploaded.

### Who does this module benefit:
[ ] end users
[X] content editors
[ ] site builders
[ ] themers
[X] developers
 
### How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
N/A.

### If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
N/A.

### What is the maintenance and support status of the module. Describe the issue queue activity.
Last release 06 Apr 2022 (last month).
20 open issues, none above normal priority.

### What permissions are needed to utilise the module (and are any new permissions provided by the module)?
'Configure Media Upload form'

### Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
N/A, it's just facilitating batch uploading.

### Is the module designed to capture anonymous user data?
N/A.

### Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
N/A.

### What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
The module has had strong community usage since implementation and has been stable.

### Additional information
Not exactly a new request, it is replacing lost functionality. Dependency drupal/dropzonejs is already included in GovCMS.

**Comment by thisisalistairsaccount** [comment]
The module can be found at https://www.drupal.org/project/media_bulk_upload

**Comment by rod-higgins** [comment]
I agree. Media bulk upload was removed with no viable replacement for the SaaS platform in the last release. Can this please be priortised as it is an important feature for content editors but also migration projects where bulk upload needs to occur on SaaS. 

Thanks.

**Comment by thisisalistairsaccount** [comment]
To update, we've added this to the product backlog for assessment

**Comment by thisisalistairsaccount** [comment]
@isaactownsend we've investigated the module internally and there's currently one issue regarding uploads and anti virus scanning which would impact our platform. One of our team has raised it on the module backlog and included a patch for review at https://www.drupal.org/project/media_bulk_upload/issues/3291228 to help alleviate the issue.

If possible, we would be looking for those with capacity and knowledge to help review the patch at ttps://www.drupal.org/project/media_bulk_upload/issues/3291228 and provide comments to encourage it be moved along at the module level. Currently this bypassing our AV scanning of files would pose a risk to our platform and a patch like this (or a further improved patch) rolled into the module would give us confidence.

**Comment by isaactownsend** [comment]
Hi @thisisalistairsaccount, the patch looks good, it seems like it originates from GovCMS Media: https://github.com/govCMS/GovCMS/blob/2.x-develop/modules/deprecated/govcms_media/src/Form/BulkUploadForm.php#L118.

That would make sense as I assume it had to have been implemented to patch bulk upload for that as well if it co-existed with Clam AV. Good to know it's tried and tested.

**Comment by rsau** [comment]
Hi
I have tested above patch and files get scanned


![image](https://user-images.githubusercontent.com/29110027/177688106-4b711e88-3cfe-4029-a0ac-c05d86ed445a.png)

**Comment by isaactownsend** [comment]
Morning,

Will this module progress to internal testing after the patch review above?

Thanks,
Isaac.

**Comment by isaactownsend** [comment]
Hi all,

Are we able to have an update on this one?

We have pressure on the team to bulk publish alot of media at regular intervals and it would be a significant benefit to have this functionality back in the distribution.

Thanks,
Isaac.

**Comment by brett-sargeant** [comment]
+1

**Comment by thisisalistairsaccount** [comment]
Hi all, I was hoping the maintainers would have been able to progress the aforementioned issue https://www.drupal.org/project/media_bulk_upload/issues/3291228 and the D10 compatibility https://www.drupal.org/project/media_bulk_upload/issues/3333898 into a new release by this point. That hasn't yet been the case and has been a blocker for progress. 

I have reached out direct to the maintainers and am exploring options around co-maintainer or other support to get this module updated, noting there are some other RTBCs in the queue.

I'm conscious this is an important aspect for site owners and want to get this moved along

**Comment by isaactownsend** [comment]
Thanks Alistair, 

Looks like the D10 compatability already has the merge request prepared; the ClamAV validation hopefully gets wrapped into a release when the maintainers respond.

Cheers,
Isaac.

**Comment by thisisalistairsaccount** [comment]
Just another update to this one, last week a D10 stable version, 3.0.1 was released. This gives us the Drupal 10 compatibility we need noting the march towards to Drupal 10 this year.

To note, a 3.0.2 release is currently in planning at https://www.drupal.org/project/media_bulk_upload/issues/3352268 which will cover our ClamAV validation, among a few other things that were also RTBC. It may have the opportunity to grab some other low hanging fruit too!

**Comment by isaactownsend** [comment]
Thanks @thisisalistairsaccount - the release is now ready: https://www.drupal.org/project/media_bulk_upload/issues/3352268#comment-15006932

Does that give the green light to push this into the distribution?
Isaac.

**Comment by brett-sargeant** [comment]
+1111111111111111111111111111111111111111111111111111111111111111111111111111111111

(does that show my interest? :) )

**Comment by thisisalistairsaccount** [comment]
Hey everyone, just to update this we are currently re-reviewing the module.

With our previous AV scanning we found files were not being checked as expected with this module. We're currently confirming its status with our new AV scanning tool.

I'm hoping we can provide an update in July on this one

**Comment by thisisalistairsaccount** [comment]
This is now available as part of the 3.14.0 release - https://github.com/govCMS/GovCMS/releases/tag/3.14.0 being deployed to SaaS sites this week.
