### ISSUE TITLE
PHP 8.1 Deprecated errors will not be fixed immediately, in the interim, hide the errors so developers can see their php deprecated erros only.

### ISSUE THREAD

**Issue by silverham** [govCMS/GovCMS#477]
@see #476

**Comment by thisisalistairsaccount** [comment]
Hi @joshua-graham-adelphi we do suppress messages in the Master environment on the platform.

For local and lower environments, these messages are on to help with development assistance.

There is a module **config_perms** that can be enabled and there is a custom there to "administer error logs". You can also set DEV_MODE to false inside the .env file.

**Comment by silverham** [comment]
Hi @thisisalistairsaccount,

I have done some testing, and the PHP errors do not appear on any GovCMS environments, neither PROD or lower Envs (checked ones in govcms5 and govcms7 clusters), but you are right for local environments.

My understanding for custom_perms is that it block access to certain paths and the "administer error logs" custom permission blocks access to the Database Logging page, however this module is not allowed to be turned on the platform (probably to save database space). So not sure if the permission is helpful on the platform.

Anyway, it seems that these errors will not proactively fixed, so we must put up with the errors that are outside of our control.

**Comment by Benjen** [comment]
Hi @thisisalistairsaccount,

We are also experiencing issues with this config_perms module on a number of DoH projects. Is creating a lot of noise on our pages. Would be great if we could get this issue resolved as not so keen on the idea of disabling error logging in our local development environment as it makes it difficult to pick up other issues.

![config_perms_warnings](https://user-images.githubusercontent.com/1292616/180337672-8f9fa583-6adc-4ed9-be49-0d680f4616ad.jpeg)
