### ISSUE TITLE
Add custom_meta module to GovCMS

### ISSUE THREAD

**Issue by naveenvalecha** [govCMS/GovCMS#577]
** What value does this module/package add to GovCMS?
Allows to add custom metatags to the pages without high-jacking the theme
** Is the module Drupal 10 compatible?
Yes
** Please provide a brief outline of what this module does.
It provides the capability to site builders to create custom metatags which could be added via the Metatag.
** Who does this module benefit:
[ ] end users
[X ] content editors
[X ] site builders
[ ] themers
[X ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
Add hook_page_attachments_alter and attach the custom metatags there but that method doesn't provide the capability to the content editors to provide the value in the metatags.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered?
The end goal could be achieved using theme but that solution doesn't offer the functionality to the content editors to update the value of the metatags.

** What is the maintenance and support status of the module? Describe the issue queue activity.
The module is actively being maintained.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
The module provides "administer custom meta tags" permissions for administering the configuration.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
No

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable?
The metatag module caters the caching. It provides additional functionality built on top of the metatag module.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
1096 sites are using it. Supported by Morpht. 

** Additional information

https://www.drupal.org/project/custom_meta

**Comment by thisisalistairsaccount** [comment]
Hi @naveenvalecha thanks for raising this item in the queue. I've added a few extra labels to the issue. 

I also note the module has now ticked over to both D10 and has a stable release. 

I've marked the label "requires more community feedback/interest" to gauge interest from others in the community on the interest and value in this module.

**Comment by brett-sargeant** [comment]
Could be useful for some sites.

**Comment by naveenvalecha** [comment]
@brett-sargeant Custom Meta module is very close to going to be included in the Metatag module. Please follow https://www.drupal.org/project/metatag/issues/3380911#comment-15647206 and post your feedback into it.
This issue could be closed after Custom Meta inclusion into Metatag.
FYI: @thisisalistairsaccount

**Comment by naveenvalecha** [comment]
@thisisalistairsaccount Custom Meta has been included in the Metatag module. https://www.drupal.org/project/metatag/releases/2.1.0 
Thank you @murraywoodman and Morpht for sponsoring their time for the contribution.

The Metatag is getting upgraded to 2.1.0 here https://github.com/govCMS/GovCMS/pull/1287 Now this functionality will be included automatically in GovCMS by an existing dependency. Now, [Site Personalization](https://www.morpht.com/drupal-personalization) will be very easy to setup for GovCMS customers.

**Comment by naveenvalecha** [comment]
Here's the upgrade guide from Custom Meta to Metatag https://www.morpht.com/blog/custom-meta-module-joins-metatag

**Comment by naveenvalecha** [comment]
@thisisalistairsaccount Here's How to guide of using the module https://www.morpht.com/blog/unleashing-power-metatag-custom-tags
