### ISSUE TITLE
Remove ga_login module

### ISSUE THREAD

**Issue by twlcox** [govCMS/GovCMS#619]
Release 2.24.0 includes the 1.0.0-alpha10 version of the TFA module this includes the merger with the [Google Authenticator login](https://www.drupal.org/project/ga_login) module.

The ga_login module is still included in composer.json but it is no longer required due to the functionality being merged with the TFA module.  As per the ga_login project page "Drupal 8 and 9 are no longer supported by the ga_login module". As such it appears ga_login should be removed.

**Comment by isaactownsend** [comment]
Assuming this is already planned for removal for the D10 release and agree it should be cleaned out from current releases if no longer in use or supported.

**Comment by thisisalistairsaccount** [comment]
Hi @twlcox we will be removing this in one of our early releases in 2023.

**Comment by thisisalistairsaccount** [comment]
Hi @twlcox just for visibility https://github.com/govCMS/GovCMS/pull/616

**Comment by twlcox** [comment]
Thanks @thisisalistairsaccount, I'll close this one.
