### ISSUE TITLE
Bug: Uninstall module with service

### ISSUE THREAD

**Issue by rsau** [govCMS/GovCMS#746]
In latest release, 2.3.0, Features module was disabled with following code

https://github.com/govCMS/GovCMS/blob/c84e16abc0d50ae28a3d8c53dfb90a3837611040/govcms.install#L223 

and 

https://github.com/govCMS/GovCMS/blob/c84e16abc0d50ae28a3d8c53dfb90a3837611040/govcms.install#L232

I am curious why  `module_installer` service is not being used so that it can remove associated config as well?
```php
\Drupal::service('module_installer')->uninstall(['SOME_MODULE']);
```

Thanks

**Comment by thisisalistairsaccount** [comment]
Hi @rsau leave it with us to check our approach on this.

**Comment by thisisalistairsaccount** [comment]
Hi @rsau its something the team is going to use going forward, thanks for the suggestion!

**Comment by rsau** [comment]
Thanks for the update @thisisalistairsaccount
