### ISSUE TITLE
Chosen library is outdated

### ISSUE THREAD

**Issue by KelvinWong** [govCMS/GovCMS#842]
The current latest GovCMS 3.2.0 is using the `harvesthq/chosen`, which is outdated and it is not compatible with the chosen module v4.0.x, and should be updated to use `jjj/chosen`

Chosen library set up in GovCMS.
https://github.com/govCMS/GovCMS/blob/3.2.0/composer.json#L21

See the library defined in the chosen_lib module:
https://git.drupalcode.org/project/chosen/-/blob/4.0.x/modules/chosen_lib/chosen_lib.libraries.yml?ref_type=heads

**Comment by mingsong-hu** [comment]
Thanks Kelvin. I just created a PR for this.
https://github.com/govCMS/GovCMS/pull/847

**Comment by thisisalistairsaccount** [comment]
Hi @KelvinWong were testing this currently and hoping to have a fix in an upcoming release

**Comment by thisisalistairsaccount** [comment]
Hi @KelvinWong we've updated Chosen as per GovCMS release 3.4.0
