### ISSUE TITLE
Add media_bulk_zip_upload module to GovCMS

### ISSUE THREAD

**Issue by larowlan** [govCMS/GovCMS#855]
** What value does this module/package add to GovCMS?
Allows content editors to create media in bulk via zip upload

** Is the module Drupal 10 compatible?
Yep

** Please provide a brief outline of what this module does.
Provides a form for content admins to upload a zip file of e.g. PDF or images.
Each one is created as a media entity.
Integrates with media form modes allowing pre-filling of other fields like author.

** Who does this module benefit:
[ ] end users
[x] content editors
[ ] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
You couldn't

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
No

** What is the maintenance and support status of the module. Describe the issue queue activity.
Very tightly focused module. Built for an Australian Uni and used extensively on sites PreviousNext maintain. 

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
Permissions to upload in bulk. Recommended to limit to content admins.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
No

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
No cache issues.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
Comes with automated tests and already in use on a number of Australian Govt sites

** Additional information

**Comment by thisisalistairsaccount** [comment]
Module can be found at https://www.drupal.org/project/media_bulk_zip_upload

Hi @larowlan were currently investigating the use of https://www.drupal.org/project/media_bulk_upload to cover this type of solution. I'd rather not have two things that do basically the same thing. 

To note this module isn't currently stable either, I'm inclined to park this while we consider Media Bulk Upload.

**Comment by larowlan** [comment]
No worries.
FWIW if the only factor was lack of stable release, we could make that happen easily enough.

**Comment by simesy** [comment]
This module would provide good usability for editors, and something that can't be done through traditional govcms theme hacking.

**Comment by thisisalistairsaccount** [comment]
So we've introduced Media Bulk Upload as part of release 3.14.0 this week at https://github.com/govCMS/GovCMS/releases/tag/3.14.0 - sites on SaaS are being updated to this release as of the time of writing.

Noting my previous comments on overlap with this and Media Bulk Upload, I think we can close this off as we've now got coverage.
