### ISSUE TITLE
Determine next steps for drupal/inline_entity_form:^2

### ISSUE THREAD

**Issue by sembrat** [govCMS/GovCMS#922]
There may be concern with using the `2.x` branch of `drupal/inline_entity_form` given the recent issues with major version releases by the active co-maintainers.

https://www.drupal.org/project/inline_entity_form/issues/2576445 should highlight the current path to stable (3.x, in this case), to which GovCMS was referenced in https://www.drupal.org/project/inline_entity_form/issues/3401656 .

**Comment by pandaskii** [comment]
Highly appreciated @sembrat 

We, from GovCMS, noticed that the 2.x branch is no longer supported starting from yesterday.

Ideally, we would prefer a smooth transition from version 2.x to 3.x. We are willing to conduct tests and code reviews to make this transition as seamless as possible.

Another option is to revert to the 1.x branch, but we have concerns about potential data issues that may arise from downgrading at this time.

Our last option is to officially declare it as 'obsolete' in our distribution and patiently wait for version 3.x to be available.

**Comment by thisisalistairsaccount** [comment]
Hi @sembrat we will aim to address one of the options mentioned by @pandaskii in our next release. Stay tuned.

**Comment by thisisalistairsaccount** [comment]
Gang, noting there's now a 3.x branch, were looking at including an update in the near future.

**Comment by thisisalistairsaccount** [comment]
Hi @sembrat as part of our release today to GitHub, we've updated Inline Entity Form to version 3.0.0-rc9 and getting off that now deprecated 2.x branch. 

This will be deployed to SaaS sites this week.
